name: Update WordPress.org Assets

on:
  push:
    branches:
      - develop
    paths:
      - '.wordpress-org/**'
      - 'readme.txt'
  workflow_dispatch:

jobs:
  assets:
    name: Update Assets
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Update WordPress.org assets
        if: ${{ secrets.SVN_USERNAME != '' && secrets.SVN_PASSWORD != '' }}
        uses: 10up/action-wordpress-plugin-asset-update@stable
        env:
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SLUG: digital-license-manager
          ASSETS_DIR: .wordpress-org
